### ISSUE TITLE
Install ProgressLabeller in Blender

### ISSUE THREAD

**Issue by godfatherqyx** [huijieZH/ProgressLabeller#1]
![QQ20221130-0](https://user-images.githubusercontent.com/53429443/204746672-9f2696f8-813a-4a14-b278-e780dd39293e.png)
Sorry to bother. Your progresslabeller is a quite good tool, so i want to use it in my work. But i meet some problems when installing progresslabeller adds-on in Blender. Our machine is Ubuntu18.04 and Blender version is 2.92 as your instruction mentioned.I also use conda environment and all dependencies are installed.At first, i thought my pycuda worked wrong, but i tested some examples and found it could work well.
![QQ20221130-1](https://user-images.githubusercontent.com/53429443/204747808-9ac60a1a-ce89-4d5b-bbec-0347495f950d.png)
I found most codes in cuda_kernel.py were annotated.Does it affect? Or I made other mistakes?

**Comment by huijieZH** [comment]
Hi,

Thanks for your interest in ProgressLabeller. From your report problem, it is probability because a mismatch of CUDA version and GPU version. Could you report your CUDA version and GPU version? Thanks.

the cuda_kernel.py file just looks like this.

**Comment by godfatherqyx** [comment]
Thanks for reply! I checked my CUDA version and GPU version. My CUDA version is 11.3 and my GPU version is Nvidia 3090. And my GPU driver version is 470. I can successfully use pytorch cuda. So the question has confused me for a long time. My pycuda version is 2022.1. Maybe it's too high?  @huijieZH

**Comment by huijieZH** [comment]
It seems the right version. Could you show the output of "nvcc -V", just make sure you set CUDA_DIR in your environment. From [here](https://askubuntu.com/questions/1301714/nvcc-fatal-value-sm-86-is-not-defined-for-option-gpu-architecture), your problem means your CUDA is old to support sm_86.

**Comment by godfatherqyx** [comment]
![截屏2022-12-01 15 31 58](https://user-images.githubusercontent.com/53429443/204993073-3a529e47-9194-4c13-b684-dd89006d96cf.png)
![截屏2022-12-01 15 33 00](https://user-images.githubusercontent.com/53429443/204993098-18e4c5e7-bcb1-4bec-9290-1b6f40fadb97.png)
@huijieZH

**Comment by godfatherqyx** [comment]
![截屏2022-12-01 15 44 58](https://user-images.githubusercontent.com/53429443/204995254-4c4d33ca-4a6a-40b0-8403-b4e0a512205a.png)

**Comment by huijieZH** [comment]
Another possible reason is that ProgressLabeller uses python in the blender, not your system's python, you may install some package in your system's python. Also, Pycuda maybe not be the necessary package you need to use if you don't use Kinectfusion.

**Comment by huijieZH** [comment]
If you like, you could send your Wechat to my email huijiezh@umich.edu for more convenient chatting.
