### ISSUE TITLE
安装过程中的问题

### ISSUE THREAD

**Issue by Gaben21** [huijieZH/ProgressLabeller#2]
请问这个是什么原因呢
![2024-01-29 11-25-07屏幕截图](https://github.com/huijieZH/ProgressLabeller/assets/63099442/a4399d04-3374-49df-ad53-4439b79ed763)

**Comment by Gaben21** [comment]
@cxt98 @huijieZH 
在make这一步出现的问题，请问如何解决呢
![2024-01-30 10-01-54屏幕截图](https://github.com/huijieZH/ProgressLabeller/assets/63099442/c0678a19-7bc2-445a-9b91-bad826002acd)

**Comment by cxt98** [comment]
看起来有两个问题，第一个像是没有clone huijie修改的repo而是原repo，所以没有对应的修改的function；第二个是在解压吧？有什么问题？

**Comment by Gaben21** [comment]
已经解决了，感谢

**Comment by Gaben21** [comment]
@cxt98 
很抱歉，再次打扰您
我在使用demo的时候又遇到了问题，在3D Reconstruction的时候报了如下错误
![625c373002bb69917bbbe2482100c74](https://github.com/huijieZH/ProgressLabeller/assets/63099442/a8eda0c1-0d97-420a-8d9d-84e569d75ece)
demo是从readme中提供的链接里下载的，该步骤之前的操作也是跟着演示里面的来执行的，请问这个是什么原因呢？

**Comment by cxt98** [comment]
看起来是没找到recon/campose.txt 我记得这个文件是跑完orbslam会生成的 你可以看看你的配置文件里写的和blender里输入的文件路径是不是有的地方不一致，也可以直接在file explorer找一下有没有这个recon文件夹，有的话应该可以在blender的文件路径里修改，然后再试一下后续步骤能不能找到

**Comment by Gaben21** [comment]
现在问题是这个报错是在我点击3D Reconstruction之后就立刻产生的，还没有开始跑orbslam
这个是Reconstruction之前datasets中recon文件夹里的内容
![1](https://github.com/huijieZH/ProgressLabeller/assets/63099442/5bb8edd5-2e47-4c91-b553-d888c4ae440f)
这个是点击3D Reconstruction之后，recon文件夹里的内容，之前的文件都消失了
![2](https://github.com/huijieZH/ProgressLabeller/assets/63099442/660e7e15-626e-45f8-b1f2-086bcd0909cf)
这个是我的配置文件configuration.json
![2024-02-01 15-01-46屏幕截图](https://github.com/huijieZH/ProgressLabeller/assets/63099442/77f0daaf-c9a2-4981-b436-f16729a81abd)
这个是blender输入文件的路径
![2024-02-01 15-02-29屏幕截图](https://github.com/huijieZH/ProgressLabeller/assets/63099442/9f986a67-60cc-43ce-bf9d-4b8bf6383972)
应该是一致，不清楚是什么问题

**Comment by Gaben21** [comment]
问题已经解决了，是ORB_SLAM3 Parameters的路径选错了，之前用的是orbslam文件夹中的ORBvoc.txt。

**Comment by jnuxzy** [comment]
> 问题已经解决了，是ORB_SLAM3 Parameters的路径选错了，之前用的是orbslam文件夹中的ORBvoc.txt。

@Gaben21 打扰了，我遇到了跟您一模一样的问题。请问您ORB_SLAM3 Parameters的路径是改为orb_slam3文件夹下的ORBvoc.txt吗？我在尝试更改路径后，仍然报错没找到campose.txt。
期待您的回复，感谢！
